### ISSUE TITLE
question_start closes client 

### ISSUE THREAD

**Issue by chesepp** [vehbiu/kahoot-py#2]
the title may be inaccurate but I've tested it and it seems that the question_start event just crashes the bot.

**Comment by vehbiu** [comment]
Do you have a stack trace? What's your error?

**Comment by vehbiu** [comment]
@chesepp Do you have a stack trace? What's the exception being thrown?

**Comment by vehbiu** [comment]
@chesepp If you do not respond, I will be closing this

**Comment by chesepp** [comment]
sorry for the late response, when the question start event occurs, it displays this from the logger. 

DEBUG:aiocometd_noloop.transports.base:Connect task finished with: {'channel': '/meta/connect', 'id': '2', 'successful': True}

**Comment by vehbiu** [comment]
What quiz are you trying to host? Could you send me the set link?

**Comment by chesepp** [comment]
https://create.kahoot.it/details/a68bedd7-4762-4535-909b-427c831af451 this one.

**Comment by vehbiu** [comment]
![image](https://github.com/user-attachments/assets/f3c24084-4039-4b84-96be-583df5ccb126)
Works on my end, are you sure you have updated to the latest version and are using [client_example.py](https://github.com/vehbiu/kahoot-py/blob/main/client_example.py)?

**Comment by chesepp** [comment]
i just updated and ran the client_example version and it works. i think i did something in my code to make it not work.

**Comment by vehbiu** [comment]
> i just updated and ran the client_example version and it works. i think i did something in my code to make it not work. 

Yeah, the old example didn't respond to the question correctly due to a bug in the index, but it shouldn't have crashed. Anything else?

If not, a star would be very much appreciated 😊

**Comment by chesepp** [comment]
what i was trying to do in my code was to create multiple bots by creating a client for each bot, but for some reason (probably because it each one uses the same client name) the clients close out once they get to question start.

**Comment by vehbiu** [comment]
> what i was trying to do in my code was to create multiple bots by creating a client for each bot, but for some reason (probably because it each one uses the same client name) the clients close out once they get to question start.

Yeah, for obvious reasons, I can't provide code for that. However, it should be easy to fix...
